### ISSUE TITLE
为什么有时候按标签屏蔽有时候没有应用效果？

### ISSUE THREAD

**Issue by a824355732** [NateScarlet/user-scripts#5]
为什么有时候按标签屏蔽有时候没有应用效果？

图1为例子视频的标签
图2为首页未屏蔽的效果
图3为屏蔽关键词的设置

![视频标签](https://github.com/user-attachments/assets/50566866-377c-4ec4-8180-0d1af90bcb98)
![未屏蔽](https://github.com/user-attachments/assets/e32c8c19-6a2f-48b1-b060-243fec9ea159)
![屏蔽设置](https://github.com/user-attachments/assets/08a530a6-e459-4705-b984-c87d070de190)

**Comment by NateScarlet** [comment]
你找错了地方了吧　这个插件我没见过
